### PR TITLE
Humanization VERY LEGIT

### PR DESCRIPTION
**Pull request by KetamineAddict**
Added:
-random extremities
-shift of gaussian distribution
-keycount last 500ms
-expand gaussian by 40% if over 4 clicks in past 500ms

### CODE REVIEW

**Comment by KetamineAddict** [comment]
[da7b2e1](https://github.com/Ciremun/freedom/pull/163/commits/da7b2e19d23fdac0e37211682d394f952526eee6)
[4bc8181](https://github.com/Ciremun/freedom/pull/163/commits/4bc8181e6d90ae83dc5cb4c0ef7f63269c09245e)

Those are unneccesary. I have changed the relax.cpp several times.

**Comment by Ciremun** [comment]
i changed my mind about pull requests, i cant accept it, sorry
first pull request was reverted, too

my reasons are: i want to code and understand it myself, and also avoid dragging additional headers, stdlib features, code style changes, its complicated
think of it as my personal hobby project

**Comment by KetamineAddict** [comment]
Alright no problem, it will just stay at my fork then. Thank you for the project though. its really cool. I will improve it myself and if you want you can have a look at it sometimes.

**Comment by GamebP** [comment]
@KetamineAddict Can you open issues on your fork?

**Comment by KetamineAddict** [comment]
sure

**Pull request closed without merging**
