### PR TITLE
Updated Readme & added Wiki.

### PR DESCRIPTION
**Pull request by GamebP**
Hello fellow developer, I truly think you need this kind of update on README.md

- [X] I have removed almost everything in READEME.md but added wiki page,
- [X] I have made two language packs inside wiki named english and russian,
- [X] I did add a Russian language pack, that who dosent know english at all.

If you dont like it, give me a comment.

### CODE REVIEW

**Comment by globlord** [comment]
alo i am new to stuff like this and dont know how to run the injector using microsoft vs i have downloaded the required build tools but dont know how to use them, any help would be appreciated :D

**Comment by Ciremun** [comment]
@globlord microsoft vs is a tool to convert source code (text) into injector+dlls  
the readme has sections [Download](https://github.com/Ciremun/freedom?tab=readme-ov-file#download) and [Build](https://github.com/Ciremun/freedom?tab=readme-ov-file#build)  
Download describes ways to obtain ready-to-use injector and dlls  
Build describes how to convert source code into executable files (to edit the program)

**Comment by globlord** [comment]
> @globlord microsoft vs is a tool to convert source code (text) into injector+dlls the readme has sections [Download](https://github.com/Ciremun/freedom?tab=readme-ov-file#download) and [Build](https://github.com/Ciremun/freedom?tab=readme-ov-file#build) Download describes ways to obtain ready-to-use injector and dlls Build describes how to convert source code into executable files (to edit the program)

aha! ive figured out what i am doing wrong thank you king

**Comment by globlord** [comment]
also is there a way in like config to make relax ur sort of randomized in 300 range?

**Comment by Ciremun** [comment]
> also is there a way in like config to make relax ur sort of randomized in 300 range?

its not there currently but I could add that

**Comment by globlord** [comment]
> > also is there a way in like config to make relax ur sort of randomized in 300 range?
> 
> its not there currently but I could add that

yeah that would be a really good feature imo, maybe if possible make it so someone could customize the threshhold for hits so someone could make it like occasionally hit 100s to make it look super legit

**Pull request closed without merging**
