### PR TITLE
Relax mod humanization

### PR DESCRIPTION
**Pull request by KetamineAddict**
Removed the linear randomization of the relax bot and replaced it with a gaussian deviation to have a more human like relax bot.

Also added a timer to the alternate option, so that only clicks under 800ms delay trigger the alternation.

### CODE REVIEW

**Comment by KetamineAddict** [comment]
If you want, I have even more humanization math implemented. 
Looks 90% like a human with random delay spikes in the plays and some extremities outside the gaussian distribution.

Then the gaussian gets shifted along the X axis every few seconds so it doesnt always stay in the middle.

**Comment by Ciremun** [comment]
thanks

**Comment by KetamineAddict** [comment]
Did you test it and like it?
If you want I can update it with my latest version.

**Comment by Ciremun** [comment]
i havent tested it, update if you want

**Pull request merged**
